[package]
name = "serde-vecmap"
description = "(de)serialize a map to an (optional) array of tuple (K,V)"
authors = ["David Ross <daboross@daboross.net>", "Éric BURGHARD <eric@itsufficient.me>"]
version = "0.1.0"
edition = "2018"

[dependencies]
serde = "1.0.130"
